DROP TABLE IF EXISTS film_genre, film_mpa, friendship, user_film_like, genres, mpas, users, films;

CREATE TABLE IF NOT EXISTS users (
                                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            email VARCHAR(64) UNIQUE NOT NULL,
                                            login VARCHAR(64) UNIQUE NOT NULL,
                                            name VARCHAR(64) NOT NULL,
                                            birthday DATE NOT NULL CHECK (birthday < NOW())
);

CREATE TABLE IF NOT EXISTS films (
                                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            name VARCHAR(64) UNIQUE NOT NULL,
                                            description VARCHAR(200) UNIQUE NOT NULL,
                                            duration INT NOT NULL,
                                            release_date DATE NOT NULL,
                                            rate REAL
);

CREATE TABLE IF NOT EXISTS mpas (
                                           id INT PRIMARY KEY AUTO_INCREMENT,
                                           name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
                                             id INT PRIMARY KEY AUTO_INCREMENT,
                                             name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_mpa (
                                            film_id INT NOT NULL REFERENCES films(id) ON DELETE CASCADE ON UPDATE NO ACTION,
                                            mpa_id INT NOT NULL REFERENCES mpas(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS film_genre (
                                            film_id INT NOT NULL REFERENCES films(id) ON DELETE CASCADE ON UPDATE NO ACTION,
                                            genre_id INT NOT NULL REFERENCES genres(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS friendship (
                                              user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION,
                                              friend_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION,
                                              status VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_film_like (
                                            user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION,
                                            film_id INT NOT NULL REFERENCES films(id) ON DELETE CASCADE ON UPDATE NO ACTION,
                                            mark INT CHECK (mark >= 1 AND mark <= 10)
);

CREATE TABLE IF NOT EXISTS director (id INT PRIMARY KEY AUTO_INCREMENT);